### ISSUE TITLE
Update "5. Security Implications When Using REST API"

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/restapi-docs#10]
5. Security Implications When Using REST API

https://doc.cuba-platform.com/restapi-7.2/?_ga=2.48141351.1890556305.1583841766-
1761876135.1554359697#security

After breaking changes in the CUBA 7.2 Security subsystem:
https://files.cuba-platform.com/cuba/release-notes/7.2/#security

this section requires rework.

We should leave old text for legacy projects which continue to use old security policy version.

For new projects there is no need to disable anything. Conversely, you need to create role and enable REST API for particular user in order to be able to use REST API.

**Comment by alexbudarov** [comment]
also update this section:
https://doc.cuba-platform.com/restapi-7.2/#usage_example

add notification "don't forget to add restapi role to the user"

**Comment by zhenyazb** [comment]
add about security scope  cuba-platform/restapi#99
