### ISSUE TITLE
Incorrect entity definition with "$"

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/restapi-docs#18]
*CUBA Platform version: 7.2.7
CUBA Studio plugin version: 15.0.SNAPSHOT2496-202
IntelliJ version: IntelliJ IDEA 2020.2 (Community Edition)*

https://doc.cuba-platform.com/restapi-7.2/?_ga=2.228382429.1590803266.1597743877-425039747.1579073124#rest_api_v2_queries_config

https://doc.cuba-platform.com/restapi-7.2/?_ga=2.228382429.1590803266.1597743877-425039747.1579073124#rest_api_v2_ex_query_get

https://doc.cuba-platform.com/restapi-7.2/?_ga=2.228382429.1590803266.1597743877-425039747.1579073124#rest_api_v2_ex_query_post

And probably somewhere else where rest-queries.xml is mentioned.

Entity definition in the code should be like ``entity="sample_Car"`` instead of ``entity="sample$Car"``

![image](https://user-images.githubusercontent.com/19840141/91052530-a2a99f00-e632-11ea-857b-b4eae2f7e6b2.png)

And in REST-query requests - too
![image](https://user-images.githubusercontent.com/19840141/91052644-ccfb5c80-e632-11ea-9e23-1884b4a8297e.png)

And in all other requests - too
![image](https://user-images.githubusercontent.com/19840141/91057125-e05cf680-e637-11ea-8530-d23daadd8817.png)

**Comment by zhenyazb** [comment]
fixed in #24
